### ISSUE TITLE
Stuck at loading step due to the loadInProgress flag

### ISSUE THREAD

**Issue by robin-obrien** [n1k0/casperjs#1421] opened 2016-02-03 11:28 UTC
In some scenario, that I am unable to find a workaround, the code gets stuck due to the flag loadInProgress that seems to be stuck in true.

This is my code:
```
casper.start('https://m.facebook.com', function() {
    this.fill("form", {
        'email':    facebookUsername,
        'pass':    facebookPassword
    }, true);
});

casper.thenOpen('https://m.facebook.com/Casper-the-Friendly-Ghost-92386373162', function () {
  this.log("Page Loaded");
  this.capture("Casper.png");
});

casper.run();
```

When you run it, the "Page Loaded" is never printed as the flag of loadInProgress is stuck on true and so the callback is never called. After 3 days (and nights...) debugging both my code and getting into CasperJS code to try and solve it, I am quite positive this is an issue.

The versions of the libraries used are CasperJS 1.1.0-beta3 and PhantomJS 1.9.8

**Comment by istr** [comment] 2016-02-03 13:37
Ok. Confirmed to fail with latest CasperJS and old PhantomJS.

However https://m.facebook.com fails to load at all with older PhantomJS engine:

```js
var casper = require('casper').create({
  verbose: true,
  logLevel: 'debug'
});

casper.start('https://m.facebook.com', function() {
  casper.waitForUrl(/^https:\/\/m.facebook.com/, function() {
    this.log("FB Loaded");
  });
});

casper.run();
```

```
ENGINE_EXECUTABLE=~/bin/phantomjs-1.9.7 casperjs frobbook.js
[info] [phantom] Starting...
[info] [phantom] Running suite: 2 steps
[debug] [phantom] opening url: https://m.facebook.com/, HTTP GET
[debug] [phantom] Navigation requested: url=https://m.facebook.com/, type=Other, willNavigate=true, isMainFrame=true
[warning] [phantom] Loading resource failed with status=fail: https://m.facebook.com/
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step anonymous 2/2: done in 485ms.
[info] [phantom] Step _step 3/3: done in 506ms.
[warning] [phantom] Casper.waitFor() timeout
[error] [phantom] Wait timeout of 5000ms expired, exiting.
Wait timeout of 5000ms expired, exiting.
```

(same for PhantomJS 1.9.6)

Works for me with latest CasperJS and latest PhantomJS (2.1.1):

```
ENGINE_EXECUTABLE=~/bin/phantomjs-2.1.1 casperjs frobbook.js
[info] [phantom] Starting...
[info] [phantom] Running suite: 2 steps
[debug] [phantom] opening url: https://m.facebook.com/, HTTP GET
[debug] [phantom] Navigation requested: url=https://m.facebook.com/, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "https://m.facebook.com/"
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step anonymous 2/2 https://m.facebook.com/ (HTTP 200)
[info] [phantom] Step anonymous 2/2: done in 2891ms.
[info] [phantom] Step _step 3/3 https://m.facebook.com/ (HTTP 200)
[info] [phantom] Step _step 3/3: done in 2911ms.
[info] [phantom] waitFor() finished in 40ms.
[info] [phantom] Step anonymous 4/4 https://m.facebook.com/ (HTTP 200)
[debug] [phantom] FB Loaded
[info] [phantom] Step anonymous 4/4: done in 2972ms.
[info] [phantom] Done 4 steps in 2991ms
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
```

**Comment by istr** [comment] 2016-02-03 13:40
Please check your test case with the latest versions of CasperJS and PhantomJS. FB tends to use all bells and whistles available and the underlying webkit engine of PhantomJS before 2.0.0 is a bit dated, to say the least.

**Comment by robin-obrien** [comment] 2016-02-03 14:12
Yes! finally, I'll recheck it now to double check, but finally it seems to be working. That was the issue, god... 3 exhausting days. Now I can get back to work.
Thank you so much!

**Comment by robin-obrien** [comment] 2016-02-03 19:39
@istr, I really appreciate your feedback! You have no idea how much... it helped me solve a very frustrating issue. 

I was wondering if you might help me with two other smaller issues following the previous one. There is the google group/mailing list, but it seems to be much less active. When I run using the save the cookie argument (--cookies-file=cookiejar.json) and of course add an 'if' statement to skip the filling of credentials if already logged in (Even something basic as fill credentials only if title is "Welcome to Facebook")

1. After I run, I always seem to get some errors loading resources when the page is getting loaded and I don't really understand why that happens.
A few examples:
1.1. [error] [phantom] Error loading resource! Error code:5, Description:Operation canceled, Resource url:https://m.facebook.com/api/
1.2. [error] [phantom] Error loading resource! Error code:5, Description:Operation canceled, Resource url:https://edge-chat.facebook.com/pull
1.3. [error] [phantom] Error loading resource! Error code:5, Description:Operation canceled, Resource url:https://m.facebook.com/chat/presence_icon.php

It is not consistent and every run it acts a little different.

2. After I run, I seem to be redirected to another page, is there a way to abort that?
For example:
[debug] [phantom] Navigation requested: url=https://m.facebook.com/xti.php?..., type=Other, willNavigate=true, isMainFrame=false

**Comment by istr** [comment] 2016-02-03 20:36
Chances to get help are better if you provably did the basic research on your own...
Searching for "Error code:5, Description:Operation canceled" leads directly to https://github.com/ariya/phantomjs/issues/12750 and https://github.com/ariya/phantomjs/issues/10389.

For in-depth direct support with your project you might want to hire me. ;-)

Closing because the initial issue could be fixed with an upgrade an [PhantomJS rejects to back-port bugfixes to 1.x](https://github.com/ariya/phantomjs/issues/10389#issuecomment-158962088).

**Closed by istr** 2016-02-03 20:36 UTC
Labels: PhantomJS 1.9.x

**Comment by robin-obrien** [comment] 2016-02-03 21:02
:+1:  
I might do that, do you work as a freelancer?
