### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by mmmeff** [n1k0/casperjs#1395] opened 2016-01-13 00:44 UTC
Title

**Comment by xuxingbgi** [comment] 2016-01-13 04:43
See #1350

**Comment by istr** [comment] 2016-01-13 08:55
Yes, duplicate of #1350. Feel free to tackle any open issue we want to have fixed for #1365 and create a PR.

**Closed by istr** 2016-01-13 08:55 UTC

**Comment by mmmeff** [comment] 2016-01-13 08:56
Thanks guys, sorry for the dupe.
