### ISSUE TITLE
Incorrect PhantomJS version installed with Homebrew

### ISSUE THREAD

**Issue by fender** [n1k0/casperjs#1146] opened 2015-02-05 16:39 UTC
When installing CasperJS view homebrew, it installs the latest PhantomJS version (2.0.0) but that doesn't seem to be supported. I was able to install via npm for now.

Brew formula:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/casperjs.rb

**Comment by rdpanek** [comment] 2015-02-06 08:53
It's possible. More info about support PhantomJS 2.0.X https://github.com/n1k0/casperjs/pull/1137

**Comment by saw** [comment] 2015-02-17 20:11
I had the same issue

**Comment by paazmaya** [comment] 2015-02-20 09:57
Someone should make a PR for the given brew formula to lock PhantomJS version in 1.9.x...

**Comment by cosmo0920** [comment] 2015-04-14 09:07
I'm waiting for PhantomJS 2.0 support....
But, sadly, I didn't see any progress for a long time about it.
 
So, I've made PR  https://github.com/Homebrew/homebrew/pull/38632 for the lock dependency for PhantomJS 1.9.8.

If CasperJS support PhantomJS 2.0.x, please send revert PR against Homebrew.

**Comment by n1k0** [comment] 2015-04-14 12:56
You did well, thanks.

**Comment by cosmo0920** [comment] 2015-04-19 11:01
Thanks to @DomT4's work https://github.com/Homebrew/homebrew/pull/38681, this issue would have been resolved.
Is there anything else that would prevent us from closing this deal?

**Comment by paazmaya** [comment] 2015-04-20 08:06
Just needs to be confirmed via clean installation of `brew install casperjs --devel`

**Comment by cosmo0920** [comment] 2015-04-20 12:25
I confirmed clean installation of `brew install casperjs --devel`:

* Homebrew has PhantomJS 2.0.0
* Casper Formula has PhantomJS 1.8.2 resource by itself

It seems that incorrect PhantomJS dependency issue is resolved.

```log
% brew info phantomjs
phantomjs: stable 2.0.0 (bottled), HEAD
http://www.phantomjs.org/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/phantomjs.rb
% brew install casperjs --devel
==> Downloading https://github.com/n1k0/casperjs/archive/1.1-beta3.tar.gz
######################################################################## 100.0%
==> Downloading https://phantomjs.googlecode.com/files/phantomjs-1.8.2-macosx.zi
######################################################################## 100.0%
🍺  /usr/local/Cellar/casperjs/1.1-beta3: 363 files, 11M, built in 16 seconds
% casperjs --version
2015-04-20 21:13:53.406 phantomjs[90468:d13] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
1.1.0-beta3
```

And minimal script http://casperjs.readthedocs.org/en/latest/quickstart.html#a-minimal-scraping-script works well (but with a few warnings...):

```log
% casperjs sample.js
2015-04-20 21:21:55.509 phantomjs[90986:d13] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
2015-04-20 21:21:56.992 phantomjs[90986:d13] CoreText performance note: Client called CTFontCreateWithName() using name "Palatino" and got font with PostScript name "Palatino-Roman". For best performance, only use PostScript names when calling this API.
2015-04-20 21:21:56.992 phantomjs[90986:d13] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.
CasperJS, a navigation scripting and testing utility for PhantomJS and SlimerJS
PhantomJS | PhantomJS
```

**Comment by DomT4** [comment] 2015-04-20 12:28
You should also be able to install Homebrew/homebrew's more recent ` PhantomJS ` and it shouldn't interfere with ` CasperJS `. CasperJS now automatically prepends the ` $PATH ` variable with its own internal version of PhantomJS during runtime.

**Comment by cosmo0920** [comment] 2015-04-20 12:41
Ah, you mean that Homebrew users can install latest PhantomJS and develop version of CasperJS at same time?
If so, this issue is ideally solved.

**Comment by cosmo0920** [comment] 2015-04-20 12:42
If not so, we need work for solving this issue....

**Comment by DomT4** [comment] 2015-04-20 12:44
Yup. You should be able to ` brew install phantomjs ` and ` brew install casperjs ` and they should never conflict or cross each other.

**Comment by cosmo0920** [comment] 2015-04-20 12:53
Thanks. Your proposal fix is really awesome!

**Comment by DomT4** [comment] 2015-04-20 12:55
It should all be fixed, but if you hit anything else funky/odd, feel free to ping me on it :).

**Comment by cosmo0920** [comment] 2015-04-20 12:56
:)

**Closed** 2015-04-20 14:15 UTC
Labels: PhantomJS

**Comment by nkoterba** [comment] 2015-05-18 18:40
So I want to use CasperJS 1.1-beta3, but with PhantomJS 2.0.

Supposedly Phantom JS versions < 1.9.7 on Mavericks OSX throw font warnings: https://github.com/ariya/phantomjs/issues/11418#issuecomment-35010263

I don't want the font warnings in my output.  However, since 
`brew install casperjs --devel` by default installs and uses PhantomJS 1.8.2, I don't know how to use the new CasperJS 1.1 AND PhantomJS 2.0.

I've installed PhantomJS 2.0 first, and then installed CasperJS, but CasperJS always pulls in and uses PhantomJS 1.8.2.

Is it possible to upgrade the dependency for the 1.1 Beta to use Phantom 1.9.7 or higher?

**Comment by DomT4** [comment] 2015-06-03 23:47
Sorry, I didn't see this till now. Super-easily you can locally modify the launcher to whichever PhantomJS you want to use. In `/usr/local/opt/casperjs/bin/*` you'll find a script which is just an `exec` script - Just change the `export PATH` line to your desired PhantomJS and you're golden.
