### ISSUE TITLE
Support for PhantomJS 2.0

### ISSUE THREAD

**Issue by Xenik007** [n1k0/casperjs#987] opened 2014-07-30 11:45 UTC
Hi, 
this isn't actually an issue, but i was wondering, when will you support the pre-release of phantomJS 2.0. Is it possible to get it running with casperJS? I get an error message requiring version 1.9....

**Comment by rdpanek** [comment] 2015-01-27 15:33
I have solved a lot of problems. I went through a lot of code. Now I have problem with upload file in PhantomJS 2.0.0 (non-develop) but I deal it. Stay tuned ;-)

**Comment by mickaelandrieu** [comment] 2015-01-27 15:34
:+1: don't wait to see this feature in casperjs  !

**Comment by rdpanek** [comment] 2015-01-28 13:08
I send pull-request https://github.com/n1k0/casperjs/pull/1137 but i don't know, why don't show here

**Comment by hasanyousuf** [comment] 2015-02-07 21:22
Any hope for support 2.0?

**Comment by yonkeltron** [comment] 2015-02-18 14:06
I have a similar issue on OSX Mavericks when I try to start CasperJS (installed from Homebrew).

```
$ casperjs --version
Couldn't find nor compute phantom.casperPath, exiting.

  /usr/local/Cellar/casperjs/1.0.4/libexec/bin/bootstrap.js:241 in loadCasper
```

My environment:
```
$ uname -a
Darwin hosty.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
$ node --version
v0.12.0
```

Any news when things will get fixed? Can I provide more information to help solve this problem?

**Comment by mickaelandrieu** [comment] 2015-02-18 14:13
@yonkeltron create your own issue.

**Comment by yonkeltron** [comment] 2015-02-18 19:11
@mickaelandrieu Thanks. Done: https://github.com/n1k0/casperjs/issues/1158

**Comment by jdunk** [comment] 2015-04-03 02:35
Is the phantomjs-2 branch dead?  Last commit was > 1 month ago, even though PhantomJS 2.0 was officially released > 2 months ago and there is no sign of anyone [else] noticing that casperjs apparently has [at least one major compatibility issue](https://github.com/n1k0/casperjs/issues/1204), i.e. error handling not only not working, but process bloat to the point of explosion when it happens..

**Comment by mickaelandrieu** [comment] 2015-04-03 11:00
@jdunk we are waiting for phantomjs 2.0.1 release **because** there is no gnu/linux build available for now.

Notice also that CasperJS 1.1 probably won't provide official support of phantomjs 2, if you must use pahntomjs 2 and want a nice api on top of it, you can use nightmarejs :)

**Comment by DarrenCook** [comment] 2015-04-03 11:10
> Notice also that CasperJS 1.1 probably won't provide official support of phantomjs 2,

I don't remember seeing any discussion on this. Can you explain why?
(E.g. is there some fundamental change between phantom 1.9.x and 2.x
APIs, that affect CasperJS?)

**Comment by mickaelandrieu** [comment] 2015-04-03 14:55
@DarrenCook yes. Coffeescript support has been removed from phantomjs2, error handling change a lot

**Comment by DarrenCook** [comment] 2015-04-03 21:07
> @DarrenCook yes. Coffeescript support has been removed from phantomjs2, error handling change a lot

Does CasperJS use Coffeescript internally? Can CasperJS patch it on to
PhantomJS, the same way SlimerJS did?
https://github.com/laurentj/slimerjs/commit/1953810acabd6df9ef6c3717c72fb585cc15eae0


Regarding error handling, which of the regression bugs is/are the problem?

https://github.com/ariya/phantomjs/issues?utf8=%E2%9C%93&q=label%3ARegression+

Is it something that stops CasperJS working, or is it more something
like the difference between PhantomJS and SlimerJS?

**Comment by jdunk** [comment] 2015-04-04 19:06
@mickaelandrieu thanks. There are linux builds available though (which is how I was able to test on my Ubuntu machine).

https://github.com/ariya/phantomjs/issues/12948#issuecomment-78181293

And Mac builds have been available.  Seems a little strange that a lack of packaged linux builds from the download page directly would be deterrent enough to halt progress on support for new error handling.

**Comment by mickaelandrieu** [comment] 2015-04-05 00:32
*especially when many (most?) developers use Macs.*  => ahahahahah !!! you made my day.

**Comment by claudioc** [comment] 2015-04-07 10:23
`brew install casperjs` right now is installing phantom2 as the dependency (and casperjs fails the phantom version check). This is not an issue with casper though, I guess.

**Comment by mickaelandrieu** [comment] 2015-04-07 11:28
@claudioc this is an issue /c @n1k0 can you check the brew package ? I don't have Apple machines to test.

**Comment by paazmaya** [comment] 2015-04-09 05:53
@claudioc the issue with Brew is definitely something that should be fixed for CasperJS `v1.1`.
#1146

**Comment by cosmo0920** [comment] 2015-04-21 00:10
@claudioc  CasperJS Formula dose not depend PhamtomJS Formula now. Could you try to update Homebrew and reinstall Casper?

**Comment by claudioc** [comment] 2015-04-21 07:48
@cosmo0920 :+1: 

```
claudioc@tiburon:~$ brew install casperjs --devel
==> Downloading https://github.com/n1k0/casperjs/archive/1.1-beta3.tar.gz
Already downloaded: /Library/Caches/Homebrew/casperjs-1.1-beta3.tar.gz
==> Downloading https://phantomjs.googlecode.com/files/phantomjs-1.8.2-macosx.zip
######################################################################## 100.0%
🍺  /usr/local/Cellar/casperjs/1.1-beta3: 363 files, 11M, built in 12 seconds
```

**Comment by n1k0** [comment] 2015-04-21 07:55
The devel version (aka casperjs v1.1-beta3) would highly benefit from using a much more recent version of PhantomJS from the 1.9.x branch. Would this be achievable?

**Comment by jdunk** [comment] 2015-05-10 03:55
@n1k0 So many comments here regarding CasperJS's 1.* branch. Isn't support for Phantom JS 2.0 reserved strictly for CasperJS 2?  If so, what's CasperJS 1.* got to do with this "support PhantomJS 2.0" ticket?

**Comment by jdunk** [comment] 2015-05-10 03:59
@mickaelandrieu

> especially when many (most?) developers use Macs. => ahahahahah !!! you made my day.

I... really don't understand what you're laughing at.  Huh?  Are you... actually unaware of how many devs use macs?

> Troll apart, we will wait for official gnu/linux support from phantomjs team before think about support it.

Well, it's no wonder with that defeatist, anti-eager attitude (and if you speak for more than yourself, invoking "we") why there's been zero progress on PhantomJS 2 support.

If you're just busy, fine, that's reasonable. But for a *developer* to poopoo the idea of working with a *released* (not even beta or rc, but *already stable released*) version simply because the ready-to-go build for his favorite OS is "unofficial" to me is antithetical to the very essence of what being a developer is.

> you can suggest and make a PR on phantomjs-2 branch if you need some improvements

That you used the phrase "some improvements" shows me you have not looked at [the major issue I originally referred to in this thread](https://github.com/n1k0/casperjs/issues/1204).  On any error, casper not only fails and freezes but it crashes your entire machine!  Not exactly trivial.

> make a PR...this is open source and open to any (new) contributors.

If my javascript skills were better, and I knew where to find PhantomJS 2's error api, I'd be in a much better position to actually do that.  At least I don't have some irrational fear of installing the linux build, which is provided by Travis CI.

**Comment by mickaelandrieu** [comment] 2015-05-10 16:19
@jdunk so...  what did you suggest to help ?

**Comment by jdunk** [comment] 2015-05-11 00:27
@mickaelandrieu See above.  ^^^  (Did you read it?)

To summarize, I suggested:

* Providing an honest, valid reason for, as you put it, not even "thinking about" supporting PhantomJS 2.0 
* Not having an irrational fear of the linux build provided by Travis CI
* Any dev who uses a mac and reads this thread may find "official" builds directly (and knows where to find linux builds)
* Looking at [the major issue](https://github.com/n1k0/casperjs/issues/1204) that I am now referencing for the third time, for a sense of importance.
* Embracing the quintessential developer attitude which *seeks out* progress and innovation, instead of standing in its way, the latter of which you are doing by implying I'm not helping at all instead of acknowledging all of the above and/or coming clean about the real reason you (and others?) refuse, in your own words, to even "think" about making changes needed so that casper doesn't explode your computer when using PhantomJS 2.

I see that you're the #2 contributor and that is very much appreciated, but that doesn't justify being snippy, dismissive, and disingenuous in response to valid points that are raised (and laughing at a very hard-and-fast reality that is macs being popular amongst developers?  What was that about?).  

If you are now too busy or have lost interest or are burnt out or (insert anybody's guess here, given lack of any direct reasonable explanation provided), once again, that's fine.  Just say so.  There is no call for coming after me for pointing it out.

I'd like to echo your own sentiment back to you ("what did you suggest to help?"). If you have nothing, that's fine. Let's let those with productive things to say do the talking.

**Comment by mickaelandrieu** [comment] 2015-05-11 08:05
@jdunk again, we (the core team) have **never** say we will support officialy phantomjs2.

And I already have provided a valid reason: we will provide support for phantomjs 2.0.1 if:
* phantomjs core team provide a stable build for gnu/linux;
* someone make a complete pull request (already done atm)
* remove all coffeescript tests, because phanyomjs2 have removed coffeescript support
* rework a little bit the error handler system
* but also, as this is a BC:
    * Make a roadmap for 2.0.x release
    * Remove testing api, move it on his own repository
    * Release a stable 1.1
    * "Embracing the quitessential developper attitude which ... "
    * Want more ?

Take one issue and provide a patch, this is the best you can do.

Thanks

**Comment by vshjxyz** [comment] 2015-08-03 16:43
Hello,

it looks like this integration will take several months (or will never happen) and I just wanted to highlight that things like phantomCSS and any kind of visual regression tool based on casperjs is breaking or can't be used in the first place as JS-only apps are being created and phantomjs < 2 renders them like they are completely broken. 

Is there any plan/ETA yet? That's basically the only reason why I've never used casperJS and it's 3+ years that SPAs are out in huge numbers (thanks to Angular/React mostly).

**Comment by webdevbrian** [comment] 2015-08-21 13:08
Really need casperJS to support Phantom2.0, the whole "1.8.2 or greater, but less than 2.0." is the silliest thing.

For people like me who can't install anything less than phantom2.0 (because it's the latest and many of our libs require 2.0 now) CasperJS is now useless until it supports 2.0.

An update with the status on that would be greatly appreciated.

Thanks!

**Comment by mickaelandrieu** [comment] 2015-08-21 13:14
@webdevbrian to be honest, this is probably won't happen. I think we should declare CasperJS abandonned /c @n1k0 .

I don't have time to maintain it since I work on BackBee CMS, you should take a look to nightmarejs if you need a wrapper of phantomjs

**Comment by webdevbrian** [comment] 2015-08-21 13:15
Awwww dang it! I was getting really excited (We'll just do it in Phantom), but loved what I saw from the documentation. That stinks!

**Comment by mickaelandrieu** [comment] 2015-08-21 13:18
yeah, sorry .. I'm sad but I don't have time for it, we probably need to search a new maintainer :/

**Comment by istr** [comment] 2015-12-01 17:23
Closed with https://github.com/n1k0/casperjs/pull/1310 and https://github.com/n1k0/casperjs/pull/1352.

Note, however, that support for phantomjs 1.9.0 and earlier is dropped.

**Closed by istr** 2015-12-01 17:23 UTC

**Comment by shailajapatil45** [comment] 2016-11-08 06:38
https://github.com/datakurre/phantomrobot
I am referring above page for installing phatomrobot.

on mac: when executing
bin/buildout

getting an error:
Updating nodejs.
Installing phantomjs.
Downloading https://phantomjs.googlecode.com/files/phantomjs-1.9.0-macosx.zip
While:
  Installing phantomjs.
Error: Error downloading extends for URL https://phantomjs.googlecode.com/files/phantomjs-1.9.0-macosx.zip: HTTP Error 404: Not Found


Could you please tell me the correct URL?

**Comment by jefleponot** [comment] 2016-11-08 08:37
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/phantomjs/phantomjs-1.9.0-macosx.zip

installation script ? What does that mean ? casperjs never install anything
Regards
