### ISSUE TITLE
CasperJS hanging on casper.start when cookies are included

### ISSUE THREAD

**Issue by UndergroundLabs** [n1k0/casperjs#1436] opened 2016-02-10 16:42 UTC
I'm using CasperJS 1.1.0-beta4 and PhantomJS 2.1.1 on OSX.

I've written a module to log into Facebook. The code is below. The code between the `if` blocks works fine, but the code between the `else` doesn't.

**fb.js**

    var require = patchRequire(require);

    /*
     * Include imports
     */
    var fs = require('fs');

    exports.login = function(username, password) {

        var cookie_file = fs.workingDirectory + '/sessions/' + username + '.txt';

        /*
         * If cookie file is not present, log in as normal
         */
        if(!fs.exists(cookie_file))
        {
             /*
             * Navigate to Facebook login page, fill in form fields, and submit login form
             */
            casper.start('https://touch.facebook.com/login', function() {
                casper.waitForSelector('input[name="email"]', function() {
                    this.fillSelectors('form', {
                        '[name="email"]': username,
                        '[name="pass"]': password
                    });

                    this.click('[value="Log In"]');
                });
            });

            /*
             * Wait for page to redirect to home.php
             */
            casper.waitFor(function check() {

                /*
                 * Check if URL contains home, or save-device. Both indicate a successful login
                 */
                var url = this.getCurrentUrl();
                return (url.indexOf('home.php') > -1) || (url.indexOf('save-device') > -1);

             }, function then() {

                /*
                 * Login was successful. Save the cookie
                 */
                fs.write(cookie_file, JSON.stringify(phantom.cookies));

            }, function timeout() {

                /*
                 * Login failed.
                 */
                this.echo(JSON.stringify({
                    'response': 'failed',
                    'message': 'Login failed. Check the account manually in a browser.',
                })).exit();
            });
        }
        else
        {
            /*
             * Account has already logged in previously. Load the cookie.
             */
            phantom.cookies = JSON.parse(fs.read(cookie_file));

            casper.start('https://touch.facebook.com/home\.php', function() {
                this.echo('Cool Beans :)');
            });
        }
    };

Here is the output:

    [info] [phantom] Starting...
    [info] [phantom] Running suite: 5 steps
    [debug] [phantom] opening url: https://touch.facebook.com/home.php, HTTP GET
    [debug] [phantom] Navigation requested: url=https://touch.facebook.com/home.php, type=Other, willNavigate=true, isMainFrame=true
    [debug] [phantom] url changed to "https://touch.facebook.com/home.php"

It doesn't even get to the `this.echo`.

In the script I include this module into, there is a `casper.thenOpen` direcly after `fb.login(username, password)`. This works if I remove the cookie as the script then goes via the `if` block. But if the cookie is present it just hangs on the `casper.start` within the `else` block and never reaches the `casper.thenOpen`.

Any ideas what's going on here? I'm pretty sure this worked on my Debian machine, as this is what I origionally developed the script on. I don't have that machine to test on though

**Comment by mickaelandrieu** [comment] 2016-02-10 16:49
Hi,

you can create an ubuntu box on cloud9 and make a rapid install:
```bash
npm install -g phantomjs && npm install -g casperjs
```

It's free, and very quick to setup ;)

**Comment by UndergroundLabs** [comment] 2016-02-10 17:00
My partner has an Ubuntu laptop that she let me use to test a moment ago. It worked perfectly! I logged in first time and it went through the `if` block. Second time it pulled the cookie from the sessions directory and continued through the script.

Now, I can't understand why this isn't working on OSX. I'm using the same versions of Casper and Phantom.

Seems like an OSX bug.

**Comment by mickaelandrieu** [comment] 2016-02-10 17:03
> Seems like an OSX bug.

probably .. can you share this issue into phantomjs repository ? I think it's not related to CasperJS, I don't have Apple computer to test/reproduce ...

Mickaël

**Comment by istr** [comment] 2016-02-10 17:04
Seems to be fashionable to try to log in to FB using CasperJS nowadays. :-D
Closing as duplicate of #1421.

**Closed by istr** 2016-02-10 17:04 UTC
Labels: OSX, PhantomJS

**Comment by UndergroundLabs** [comment] 2016-02-10 17:07
@istr regardless, it's still a bug and only applies to OSX. I am not sure why this is closed when it works on Debian/Ubuntu but not OSX. I am using latest versions of Phantom and Casper.

CasperJS has other uses aside from testing ;) I use it for web automation and testing. It's awesome :D

**Comment by mickaelandrieu** [comment] 2016-02-10 17:10
@UndergroundLabs not realy closed, closed in favor of #1421 
(so yes, we keep in mind your feedback, thank you ! := ) )

**Comment by istr** [comment] 2016-02-10 17:11
Ok, re-open this if you deem this an OS/X specific CasperJS bug (that is really unrelated to the PhantomJS build on OS/X), and come up with a test case that works on a site other than FB.

Please note that it violates [Facebook's terms](https://www.facebook.com/terms) in nearly all cases to harvest their website using any kind of automation:

>  3 Safety
> [...]
>  2 You will not collect users' content or information, or otherwise access Facebook, using
> automated means (such as harvesting bots, robots, spiders, or scrapers) without our prior
> permission.

**Comment by UndergroundLabs** [comment] 2016-02-10 17:13
@mickaelandrieu It seems to be a different issue though. The resolution to issue #1421 is resolved by upgrading. I am already using the latest versions.

@istr I am writing scripts to update my Facebook status with images I save throughout the day to automatically share them on my wall. The scripts run on a cron job every 30 minutes and any new images are uploaded to my Facebook wall.

I was stating I use it for web automation. Which this is :)

**Comment by istr** [comment] 2016-02-10 17:17
@UndergroundLabs 
> The scripts run on a cron job every 30 minutes and any new images are uploaded to my Facebook wall.
> 
> I was stating I use it for web automation. Which this is :)

I am not a lawyer, but if I read the cited paragraph of the terms correctly, this is expressly forbidden by FB's terms ("You will not [...] otherwise access Facebook, using automated means [...]").

However, from your description it seems to be a problem with the PhantomJS build on OS/X. It would be great (and we would really appreciate) if you could verify this
- using your test against plain PhantomJS on OS/X
- using a test case that isolates the cookie problem without using FB and with using CasperJS

Thank you. :-)

**Comment by UndergroundLabs** [comment] 2016-02-10 17:19
@istr I will knock up a script on my server to replicate login, and test again with both Phantom and Casper.

**Comment by istr** [comment] 2016-02-10 17:20
Great! Thanks a lot for support and understanding.
