### ISSUE TITLE
Cannot access HTTPS elements

### ISSUE THREAD

**Issue by O0mix0O** [n1k0/casperjs#1520] opened 2016-04-11 20:14 UTC
Hi all,

Very new to CasperJS and seem to have fallen at the first hurdle...
Trying to access any site with HTTPS results in me not being able to retrieve the elements, which I kind of need...

Been trawling the internet for the past couple of hours trying:

- 
-     --ignore-ssl=true
-     --ignore-ssl-errors=true
-     --web-security=no
-     --ssl-protocol=tlsv1
-     --ssl-protocol=any

all in varying combinations before and after 'myfile.js', with no joy.

I'm hoping someone on here can call me an idiot and give me a simple solution :)

Cheers, Mix

----------------
Following the quickstart guide on the site, my code is as follows:

var casper = require('casper').create();

casper.start('https://www.google.co.uk/#hl=en', function() {
    if (this.exists('div.ctr-p')) {
        this.echo('Found');
    } else {
        this.echo('Not Found');
    }
});

casper.run();

Windows 7 64bit
PhantomJS - **1.9.1** & **2.1.1**
CasperJS - **1.1 beta3** & **1.1 beta5**

(Copied here as it seems more populated than the google group)

**Comment by mickaelandrieu** [comment] 2016-04-11 21:07
When asking for help, please ask your question [on the mailing list ](http://groups.google.com/group/casperjs) first.

If you feel that you need to report an issue against CasperJS (and you are sure that it is not a problem specific to your installation), please include at least:
- the platform you are running on (like here: CentOS)
- the CasperJS version you are using
- the engine type and version you are using
- a minimal example script and/or description of the specific situation that helps to *reproduce* your problem

Thank you.

(Feel free to re-open this issue if you come back with more specific information and asking on the mailing list did not lead to a solution)

**Comment by mickaelandrieu** [comment] 2016-04-11 21:20
Hi @O0mix0O, sounds like a protection from Google website.

I've got the same result on an ubuntu computer so I don't think it's Windows related.

I can access the website from my own tests, but not with the same HTML (for instance I get the title and the current url, also I don't have any error).

Well ... can you test the same code with phantomjs ?

**Comment by istr** [comment] 2016-04-12 07:52
This is definitely not an HTTPS issue, but an issue with google's click tracking logic.

If you change the protocol e.g. in https://github.com/n1k0/casperjs/blob/master/samples/googlepagination.js#L51 to ```https``` the sample still works like expected.

Changing the title of the issue and closing as off-topic (specific use case for google).

**Closed by istr** 2016-04-12 07:52 UTC
Labels: Hard to Fix, Help Request

**Comment by O0mix0O** [comment] 2016-04-12 08:29
Hi again,

Thank you both for your responses.

@mickaelandrieu I will test the code with PhantomJS this morning and see if I get anything different.
However, I feel a bit of a fool currently as I changed the site to Google a method of quickly explaining my issue... 

I am actually trying to access car insurance comparison sites e.g. Compare the market, and Money supermarket, to automate the process of obtaining quotes. 
E.G.
var casper = require('casper').create();

casper.start('https://www.moneysupermarket.com/shop/car-insurance/questionset/#?step=highimpactquestions', function() {
    if (this.exists('h1.section-heading')) {
        this.echo('Found');
    }
    else
    {
    	this.echo('Not Found');
    }
});

casper.run();

//https://www.moneysupermarket.com/shop/car-insurance/questionset/#?step=highimpactquestions
//h2.msm-title title-lg-left title-md-left title-xs-center 

Sorry for the mess around.
Thanks

**Comment by istr** [comment] 2016-04-12 09:02
@O0mix0O 

> Sorry for the mess around.

No problem at all -- I cannot find the h1 tag in the page with vanilla Chrome, but the h2 renders.

Note that
- CasperJS is asynchronous. You almost always want to wait for something (to happen / occur) before testing and/or proceeding.
- your page is a freakin' angularJS monster, so it does not work with older PhantomJS versions

The following works for me with CasperJS current master and PhantomJS 2.1.1:

```js
var casper = require('casper').create();

casper.start('https://www.moneysupermarket.com/shop/car-insurance/questionset/#?step=highimpactquestions');
casper.waitForSelector('h2.msm-title.title-lg-left.title-md-left.title-xs-center', function() {
  this.echo('Found');
});

casper.run()
```

**Comment by O0mix0O** [comment] 2016-04-12 09:25
@istr 
Sorry again,, you can't find the h1 because I didn't include the correct URL! (https://m.quote.comparethemarket.com/Car/about-your-vehicle/vehicle-details)

Thanks for the tips, I'll be sure to include 'waitForSelector' in future and use the latest Phantom/Casper. 

Your code (obviously) works a treat, thank you.
I tried changing the URL and selector to compare the market, and receive the message "Wait timeout 500ms expired, exiting", so I will use money supermarket as you've proven that one works.

`var casper = require('casper').create();

casper.start('https://m.quote.comparethemarket.com/Car/about-your-vehicle/vehicle-details');
casper.waitForSelector('h1.section-heading', function() {
  this.echo('Found');
});

casper.run()`

Thanks again for your time and patience.
