### ISSUE TITLE
Stuck at loading step due to the loadInProgress flag

### ISSUE THREAD

**Issue by robin-obrien** [n1k0/casperjs#1420] opened 2016-02-03 09:45 UTC
In some scenario, that I am unable to find a workaround, the code gets stuck due to the flag loadInProgress that seems to be stuck in true. 

This is my code:
```
casper.start('https://m.facebook.com', function () {
  this.sendKeys("input[name='email']", facebookUsername);
  this.sendKeys("input[name='pass']", facebookPassword);
  this.thenClick("button[name='login']");
});

casper.thenOpen('https://www.facebook.com/Casper-the-Friendly-Ghost-92386373162', function () {
  this.log("Page Loaded");
});

casper.run();
```

When you run it with the cookie command line parameters --cookies-file=cookiejar.json, it would work the first time (When there is no cookie), but will get stuck on the second time.
On the second time, the "Page Loaded" is never printed as the flag of loadInProgress is stuck on true. The problem occurs in some sites, while others it does not. In the URL in this example, it does occur.

**Comment by istr** [comment] 2016-02-03 10:12
Probably a duplicate of #1061. I bet that the form does not exist in DOM when entering the page w/ cookie set. Any reason you don't use ```fillform()``` ?

Closing as help request that belongs to [the mailing list](https://groups.google.com/forum/#!forum/casperjs).

Feel free to re-open if you can elaborate on the failing test case a bit more (provide CasperJS version and engine with version information).

**Closed by istr** 2016-02-03 10:12 UTC
Labels: Help Request

**Comment by robin-obrien** [comment] 2016-02-03 10:40
I added the code that fills the form as a helper, but there is no issue there. The issue is related to loading of other pages that are stuck during the in loading because the flag loadInProgress does not change back to false once the page is already loaded.

The versions of the libraries used are CasperJS 1.1.0-beta3 and PhantomJS 1.9.8

**Comment by robin-obrien** [comment] 2016-02-03 11:23
Never mind, I'll just create a new one with fillform, which doesn't work as well
