### ISSUE TITLE
`fill` populates fields, but then `assertField` fails with a `null` value

### ISSUE THREAD

**Issue by derekr** [n1k0/casperjs#509] opened 2013-06-18 17:12 UTC
I can't seem to get this assertion to pass. I've added other asserts for verifying the existence of the fields and some other things to try to get this to work, but no luck. I feel like I might be overlooking something obvious.

**test_file.js**

```js
var dropdownBtn     = '.btn.dropdown-toggle';
var signinForm      = '#signin-form';
var signinDropdown  = '.dropdown-menu';

casper.start(host + '/');

casper.then(function () {
    this.test.assertUrlMatch(host, 'Guest should not be redirected');
    this.test.assertExist(signinForm, 'Signin form exists');
    this.test.assertExist(dropdownBtn, 'Signin button exists');
    this.test.assertExist('[name="nickname"]', 'Nickname field exists');
    this.test.assertExist('[name="password"]', 'Password field exists');
});

casper.thenClick(dropdownBtn, function () {
    this.test.assertVisible(signinDropdown);

    this.fill(signinForm, {
        'nickname':    'bleep',
        'password':    'bloop'
    }, false);

    this.test.assertField('nickname', 'bleep'); // undefined
    this.test.assertField('password', 'bloop'); // undefined
});

casper.run(function () {
    this.test.renderResults(true);
});
```

**login.html**

```html
<div class="dropdown-menu allow-click">
    <form method="post" action="#" id="signin-form">
        <div class="controls nickname">
            <label for="field-signin-nickname">Nickname</label>
            <input type="text" name="nickname" id="field-signin-nickname">
            <img class="maker-image">
        </div>
        <div class="controls password">
            <label for="field-signin-password">Password</label>
            <input type="password" name="password" id="field-signin-password">
        </div>
        <div class="controls pull-right">
            <input id="signin-btn" type="submit" class="btn btn-primary submit" value="Go!">
        </div>
    </form>
</div>
```

**output**

```shell
Test file: test/functional/test_file.js
PASS Guest should not be redirected
PASS Signin form exists
PASS Signin button exists
PASS Nickname field exists
PASS Password field exists
PASS Selector is visible

FAIL "nickname" input field has the value "bleep"
#    type: assertField
#    subject: false
#    inputName: "nickname"
#    actual: null
#    expected: "bleep"
FAIL "password" input field has the value "bloop"
#    type: assertField
#    subject: false
#    inputName: "password"
#    actual: null
#    expected: "bloop"
FAIL 8 tests executed in 10.252s, 6 passed, 2 failed.

Details for the 2 failed tests:

In test/functional/session_signin.js:0
   assertField: "nickname" input field has the value "bleep"
In test/functional/session_signin.js:0
   assertField: "password" input field has the value "bloop"
```

Also the failed screenshot shows the fields have been populated.

![screen shot 2013-06-18 at 10 12 01 am](https://f.cloud.github.com/assets/22249/670036/4725213a-d83a-11e2-8ce6-b83c73cc8f08.png)

**Comment by Rykus0** [comment] 2015-04-27 17:37
Have you tried moving the assertions into a separate step?  It's possible the assert is happening before the fields are actually filled.  

```
casper.thenClick(dropdownBtn, function () {
    this.test.assertVisible(signinDropdown);

    this.fill(signinForm, {
        'nickname':    'bleep',
        'password':    'bloop'
    }, false);
});

casper.then(function(){
    this.test.assertField('nickname', 'bleep'); // undefined
    this.test.assertField('password', 'bloop'); // undefined
});
```

**Comment by istr** [comment] 2015-12-05 14:29
Yes. Even CasperJS' own test suite suffered from this problem, but it is fixed in current master.
(```tests/suites/casper/formfill.js``` line 31).

As issues with timing / asynchronous behavior of the test subject seem to be very common, we definitely need to improve on the documentation here.

**Comment by RachelSatoyama** [comment] 2015-12-12 00:01
@istr I'm not sure I understan, here's what on line 31 (https://github.com/n1k0/casperjs/blob/master/tests/suites/casper/formfill.js#L31):

```
function testUrl(test) {
    casper.waitForUrl(/(^\?|&)submit=submit($|&)/, function() {
        test.assertUrlMatch(/email=chuck@norris.com/, 'input[type=email] field was submitted');
        test.assertUrlMatch(/password=chuck/, 'input[type=password] field was submitted');
        test.assertUrlMatch(/content=Am\+watching\+thou/, 'textarea field was submitted');
        test.assertUrlMatch(/check=on/, 'input[type=checkbox] field was submitted');
        test.assertUrlMatch(/choice=no/, 'input[type=radio] field was submitted');
        test.assertUrlMatch(/topic=bar/, 'select field was submitted');
        test.assertUrlMatch(/multitopic=bar&multitopic=car/, 'multitopic select fields were submitted');
        test.assertUrlMatch(/strange=very/, 'strangely typed input field was submitted');
    });
}
```
This has nothing to do with the bug reported. I've also encountered this behavior and timing does not help.

**Comment by istr** [comment] 2015-12-16 18:20
@RachelSatoyama You're right -- the timing issue is only relevant when checking for values in the URL after submitting the form. Alas, I am unable to reproduce the filed bug, but I have a suspicion why you're encountering that problem:

__tl;dr: probably you have multiple ```input``` elements in your DOM with the same ```name``` attribute__

@derekr Obviously the presented HTML does not match your presented test case. I copied over your snippets 1:1 and integrated it into the test suite. The "click to drop down the form" part is not present in your markup.

I added the following to ```tests/suites/casper/formfill.js```:

```js
casper.test.begin('#509 fill failure', 6, function(test) {
    var signinForm      = '#signin-form';
    var signinDropdown  = '.dropdown-menu';

    casper.start('tests/site/issue-509-login.html');

    casper.then(function () {
        this.test.assertExist(signinForm, 'Signin form exists');
        this.test.assertExist('[name="nickname"]', 'Nickname field exists');
        this.test.assertExist('[name="password"]', 'Password field exists');
        this.test.assertVisible(signinDropdown);

        this.fill(signinForm, {
            'nickname':    'bleep',
            'password':    'bloop'
        }, false);

        this.test.assertField('nickname', 'bleep'); // undefined
        this.test.assertField('password', 'bloop'); // undefined
    });

    casper.run(function () {
        this.test.renderResults(true);
    });
});
```

and added a new file ```tests/site/issue-509-login.html``` having the contents:

```html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>CasperJS test form</title>
</head>
<body>
<div class="dropdown-menu allow-click">
    <form method="post" action="#" id="signin-form">
        <div class="controls nickname">
            <label for="field-signin-nickname">Nickname</label>
            <input type="text" name="nickname" id="field-signin-nickname">
            <img class="maker-image">
        </div>
        <div class="controls password">
            <label for="field-signin-password">Password</label>
            <input type="password" name="password" id="field-signin-password">
        </div>
        <div class="controls pull-right">
            <input id="signin-btn" type="submit" class="btn btn-primary submit" value="Go!">
        </div>
    </form>
</div>
</body>
</html>
```

This test passes with a checkout from the current master.

Because the markup you presented is obviously not complete, your problem is not reproducible here.
You are using the simple form of ```test.assertField()``` without specifying the target form you want to test. This variant collects values from *all* input fields matching this name. Probably your markup has got another login form using the same input field name attributes somewhere.

In this case ```getFieldValue```
- finds multiple fields with the the same name
- calls the internal function ```getMultipleValues(inputs)``` on all your inputs
- returns nothing, because this only works with inputs of type ```radio``` or ```checkbox``` (https://github.com/n1k0/casperjs/blob/master/modules/clientutils.js#L591)

So, if you encounter this issue: please check if your DOM has multiple input elements sharing the same name attribute. If so, pass your specific form selector to the ```options``` parameter of ```assertField```.

I am closing this because it is not reproducible, the minimal test case passes and it seems to be specific to your test case that is not presented completely here. @RachelSatoyama feel free to re-open with a minimal test case that demonstrably has no duplicate input elements in DOM and demonstrates your issue.

**Closed by istr** 2015-12-16 18:20 UTC
Labels: Documentation
