### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DimitryDushkin** [n1k0/casperjs#1126] opened 2015-01-16 09:16 UTC
Hi there!

Really great software, very handy! But why no new release for more then a year?

**Comment by paazmaya** [comment] 2015-01-16 11:38
See #1117

**Comment by jefleponot** [comment] 2015-01-16 11:48
Please merge my branchs "Link text" and "popups"

**Comment by n1k0** [comment] 2015-01-16 12:40
Duplicate of #1117.

**Closed by n1k0** 2015-01-16 12:40 UTC
