### ISSUE TITLE
Relative path to phantomjs

### ISSUE THREAD

**Issue by StreetStrider** [n1k0/casperjs#861] opened 2014-03-18 07:57 UTC
Good day.
I've installed casper via npm. It installs phantom as dependency.
Both packages register their binaries in appropriate `.bin`.
However, casper uses global `phantomjs` reference:
https://github.com/n1k0/casperjs/blob/master/bin/casperjs#L137
So I have both packages ready to go, but can't start casper:
`Fatal: [Errno 2] No such file or directory; did you install phantomjs?`

**Comment by mudenglong** [comment] 2015-02-05 15:16
phantomjs = require 'phantomjs'
    process.env.PHANTOMJS_EXECUTABLE = phantomjs.path

add to which file? more detail please...

**Comment by mudenglong** [comment] 2015-02-05 16:01
I modify .bin/casperjs 

    CASPER_COMMAND.extend([                          
        os.path.join(CASPER_PATH, 'bin', 'bootstrap.js'),
        '--casper-path=%s' % CASPER_PATH,
        '--cli'
    ])
    CASPER_COMMAND.extend(CASPER_ARGS)

    # add here
    CASPER_COMMAND[0] = './node_modules/casperjs/node_modules/.bin/phantomjs'   
 
    try:
        os.execvp(CASPER_COMMAND[0], CASPER_COMMAND)

If use the `PHANTOMJS_EXECUTABLE` env variable, need add to which line  ? 

not good at python and English

**Comment by rdpanek** [comment] 2015-02-06 08:58
My usecase and problem.

I have installed more version of Phnatomjs and for work with CasperJS I must:

$ sudo ln -s ./test_tools/phantomjs1.9.7/bin/phantomjs /usr/local/bin/phantomjs
$ casperjs selftest

then

$ sudo rm -rf /usr/local/bin/phantomjs
$ sudo ln -s ./test_tools/phantomjs2.0.0/bin/phantomjs /usr/local/bin/phantomjs
$ casperjs selftest

This usecase is lengthy

**Comment by natostanco** [comment] 2015-02-26 10:12
on winz gotta add phantomjs to env path

`C:\Users\francesco\Desktop\SPM\node_modules\phantomjs\lib\phantom`

**Comment by oncletom** [comment] 2015-02-26 10:16
You can also do `PHANTOMJS_EXECUTABLE=/test_tools/phantomjs1.9.7/bin/phantomjs casperjs selftest`. You do not need to symlink all the time unless you want to provide a global phantom executable.

**Comment by JoshWillik** [comment] 2015-07-25 14:05
Is there any recent movement on this issue?

**Comment by istr** [comment] 2015-12-01 18:40
@rdpanek your use case is very similar to what automated testing does (see [.travis.yml](https://github.com/n1k0/casperjs/blob/master/.travis.yml)). You could go along the lines @oncletom proposes or mimic what testing within travis-ci does.

npm does not support installing multiple concurrent versions as a dependency anyway (and imnsvho that would aggravate the current multi-version, multi-dependency mess npm produces, a lot).

Packaging [for various platforms and package managers like slimerjs does](
https://slimerjs.org/download.html) is a major (ongoing) effort. If you have a look at the various versions of both supported engines, you'll find that selecting the correct one for your setup is still adventurous, due to various regressions between major, minor, (and even patch) versions.

So my proposal would be to
- drop support for npm-packaged engines as a dependency completely
- drop the npm depency from ```package.json```
- document that you need to install your engine to be in your ```PATH``` (be it system-wide or local to a user) or select your engine using ```ENGINE_EXECUTABLE```
- leave it completely up to the user how to install the engine (and what version), be it from source or using ```npm -g```, ```brew```, ```dpkg```, ```apt```, ```rpm```, ```yaourt``` and whatnot

Any thoughts? (esp. @hexid , @paazmaya)

**Comment by istr** [comment] 2015-12-31 18:23
Could you please check if [this recently merged PR](https://github.com/n1k0/casperjs/commit/ba4f1d75eed9b5a02770c0ec43e423db35b32947) fixes this issue?

**Comment by BIGjuevos** [comment] 2016-03-18 21:26
@istr I think this is worthy of being closed.  There is a known easy workaround (setting environment variable) and it looks like #1387 solves the problem.

What do you think?

**Comment by istr** [comment] 2016-03-22 09:59
@BIGjuevos I guess you're right and the inactivity after my call for re-check is quite long.

Closing.

**Closed by istr** 2016-03-22 09:59 UTC
Labels: Qualified

**Comment by amaschas** [comment] 2016-06-20 20:12
Setting the ENV variable isn't really a great solution to this problem. Karma has managed to implement a solution that allows for the use of PhantomJS from within node_modules entirely within the local directory. This is a huge benefit because it means build maintainers can entirely automate the setup for the testing process.

**Comment by istr** [comment] 2016-06-29 19:45
@amaschas I would prefer to open a new issue with a clear scope. Reverting to pre-installing a fixed-version engine is not an option imho. What we *could* do is to support searching for {place-of-casperjs-installation}/bin/phantomjs first. I thought that this would be the default behavior anyway. If this is not a case, please open an issue that states (and demands) exactly that.

A PR that addresses this would be highly welcome as well.

**Comment by ek121268** [comment] 2017-09-09 19:07
Stupid question - i am over the path related issue, but when running either selftest or the sample.js test i get nothing thrown into the console, what else am i missing?  this is my command:
../../phantomjs/bin/phantomjs ./casperjs test ../tests/selftest.js
