### ISSUE TITLE
Weird bug regarding download function

### ISSUE THREAD

**Issue by eloitay** [n1k0/casperjs#1188] opened 2015-03-20 02:42 UTC
When I do a .download with casperJS, sometime it seems to fail with zero byte file. I notice the following behavior, it seems that the file can be either a small one or a big one but for the bigger file it seems to happen more frequently. 
I did a network trace using charles proxy to see if the file did finish downloading, it seems none of them fail or at most 1 or 2 every 100 sampling of zero byte files was caused by network time out. It really puzzle me that beyond the file downloading timing out how else would it fail with zero byte written since I am running on top of a SSD I seriously doubt that the IO queue is so choked that it time out writing the content.
One more finding that I get recently is, let say I asked casperjs to download 100 images, it will probably get like 80 to 90 fine, 10 to 20 will be zero byte. 
So the interesting part is if I delete those 0 bytes and rerun the same script I may be able to get like another 10 or so. Typically the max improvement I can get is 3 times, if the same image failed 3 times, it is likely that it will never complete the download.

**Comment by paazmaya** [comment] 2015-04-10 08:03
Could you provide a minimal working example that reproduces this bug?

**Comment by eloitay** [comment] 2015-04-10 08:08
Hi
Actually it can be any script at all because it is something within the download function that is causing this to happen and considering if I keep calling the same function to download different file eventually it will happen. How I am fixing this issue now is after download I will check if it is 0 byte if yes I will delete the file and download again. Sometime it takes only 1 try to fix it some 2. 
I cannot seems to find any concrete proof of factors that might affect the chance of this happening.

**Comment by istr** [comment] 2015-12-07 14:12
Even though this issue predates #1342, I am closing this as a duplicate, because the root cause and a potential bug-fix is given there.

**Closed by istr** 2015-12-07 14:12 UTC
