### ISSUE TITLE
Clicking checkbox on a particular webpage not triggering events as it does in browser

### ISSUE THREAD

**Issue by mandeepm91** [n1k0/casperjs#1338] opened 2015-10-25 07:03 UTC
I am trying to automate a process in CasperJS. However, I am facing some discrepancy between the behavior on a real browser vs the same in CasperJS. Strange thing is that I am facing this issue when I use PhantomJS as the engine but if I use SlimerJS, then it works fine. 

Here is my script:

    var casper = require('casper').create({
    	"waitTimeout": 10000
    });
    
    var inputElements = {
        "url": "http://www.jabong.com/incult-Tapered-Jeans-In-Indigo-1032119.html?pos=4",
        "size": "34",
        "address": {
            "email": "someemail@xyz.com"
        }    
    }
    
    casper.options.viewportSize = {width: 1679, height: 902};
    
    casper.start(inputElements.url, function (){
    	this.wait(10000, function (){
    		console.log("loaded");
    	})
    });
    
    var x = require('casper').selectXPath;
    
    var sizeToSelect = inputElements.size;
    
    // select size
    casper.thenClick(x("//*[contains(@class,'size-desktop')]//"+
      "li[contains(@class,'first') and contains(@class,'popover-options')]//"+
      "span[contains(text(),'"+sizeToSelect+"')]/"+
    ".."));
    
    // add to bag
    casper.thenClick(x("//*[@id='add-to-cart']"));
    
    // view cart
    casper.thenClick(x("//*[@id='header-bag-sec']/a"))
    
    // take a screenshot
    casper.then(function() {
    	console.log("saving screenshot");
      this.capture('../../1_view_cart.png');
    });
    
    casper.then(function() {
      console.log('clicked ok, new location is ' + this.getCurrentUrl());
    });
    
    // place order
    casper.then(function (){
    	this.click("[href='https://www.jabong.com/checkout/']");
    })
    
    // take a screenshot
    casper.then(function() {
    	console.log("saving screenshot");
      this.capture('../../2_address_details.png');
    });
    
    casper.then(function (){
    	this.sendKeys("#login-email", inputElements.address.email);
    })
    
    casper.then(function (){
    	this.click("#do-guest-checkout");
    });
    
    // take a screenshot
    casper.then(function() {
    	console.log("saving screenshot");
      this.capture('../../3_guest_checkout.png');	
    });
    
    casper.waitFor(function check() {
        return this.evaluate(function() {
            return document.querySelector('#btn-login-checkout').textContent == "Continue as Guest";
        });
    }, function then() {
        this.click('#btn-login-checkout');
    });
    
    
    casper.run();

On the last page, clicking on checkbox "Checkout as Guest" on a browser removes the password input field and changes the text of the Login button to "Continue as Guest". Attached screenshot:

[![enter image description here][1]][1]

However, in CasperJS, the password input field and the Login button are not changing. Any idea what am I doing wrong ?

[![enter image description here][2]][2]

  [1]: http://i.stack.imgur.com/Uzp0H.png
  [2]: http://i.stack.imgur.com/peWvi.png

**Comment by mandeepm91** [comment] 2015-10-25 08:02
Strangely, if I use xpath selector instead of CSS selector, its working fine

**Comment by n1k0** [comment] 2015-10-25 08:05
PhantomJS has many quirks when it comes to CSS; good news switching to XPath solves the issue. Anyway, this is probably a PhantomJS issue rather than a CasperJS one :)

**Comment by mandeepm91** [comment] 2015-10-25 10:52
I faced similar issue in PhantomJS as well on this page. Was not able to click the checkbox while using DOM's mouse click event. Then used an alternative approach of getting the bounding rectangle's coordinates and using the `sendEvent` function of PhantomJS. I'm glad xpath selectors are working fine in CasperJS. Now I am stuck at another page where I am not able to fill the form elements using the `sendKeys` function. Tried both xpath and css and neither seems to work. Any known issue like this in general ?

**Comment by jcrben** [comment] 2015-10-25 17:46
I would suggest trying PhantomJS 2.0. If that works, maybe pitch in to help port this to 2.0 which seems to be close.

**Comment by jcrben** [comment] 2015-10-25 18:16
If the only issue was a typo, I would close it. If you're having issues, I hear PhantomJS 2.0 is generally more reliable, though you should look at its regressions.

**Comment by mandeepm91** [comment] 2015-10-25 18:20
No, typo was just for the second problem I mentioned. The original problem that I faced still persists while using CSS selectors. Switching to XPATH did solve that problem though.

Regarding PhantomJS 2.0, I tried that yesterday but got an error :  

```
"CasperJS needs PhantomJS v1.x
```

**Comment by jcrben** [comment] 2015-10-25 18:43
You can try the experimental branch suggested [here](https://github.com/n1k0/casperjs/issues/1327#issuecomment-145191436) or try to do what you're doing with the lower level PhantomJS API.

**Comment by mandeepm91** [comment] 2015-10-29 20:21
Closing the issue since it is specific to PhantomJS and not CasperJS. Using the xpath selector solves the problem though.

**Closed** 2015-10-29 20:20 UTC
