### ISSUE TITLE
Is CasperJS project "abandoned"?

### ISSUE THREAD

**Issue by DarrenCook** [n1k0/casperjs#1299] opened 2015-08-21 13:42 UTC
In #987 Mickaël Andrieu suggests CasperJS should be considered abandoned.

There are 5 people listed at https://github.com/n1k0/casperjs#team
Could you remove yourself (or respond here) if you no longer use it, or have time for maintaining.
@n1k0 @hexid @laurentj @mickaelandrieu @mduvall 

(If you've abandoned CasperJS because you are using something better, it'd be great to hear what and why. Maybe the CasperJS project does deserve to just fade away!)

I see there is a backlog of 273 issues and 56 pull requests... that does kind of look abandoned, doesn't it. But 56 pull requests also suggests finding a new maintainer should not be impossible.

Latest CasperJS is working fine with SlimerJS.
I think the hold-up with PhantomJS 2.0 support (which is clearly the most urgent and important issue) is just a technicality of refusing to support it because PhantomJS 2.0 does not have a published Ubuntu binary? And then a bit of code tidyup and doing a new release? I wonder if any of those 56 pull requests help??

**Comment by hexid** [comment] 2015-08-21 17:49
@DarrenCook I think the biggest issue at play here is that most of the maintainers are busy with other things (myself included).
I had worked on v2.0 support about a year ago and was not aware that they had finally released a stable version. I have just uploaded an updated version of this [here](/n1k0/casperjs/tree/phantomjs2), however there are tests failing (there seems to have been a change to how the file chooser is handled in v2.x).

If you could take a look at this version and let me know how it works, that would be great.
If there is demand, then I can try to work on getting this working with PhantomJS 1.x, but for the time being it will only work with 2.x.

**Comment by kenma9123** [comment] 2015-08-23 14:44
I'm also interested for PhantomJS 2.0 support. So I'm hoping for a new maintainer if the old folks were really busy on some other things.

@hexid does your version supports shadow DOM? With the current state of casperjs. Pages built with reactjs unable to render elements properly. Do you have any comments on that? Will it support if we moved to 2.0? maybe your version can do it?

**Comment by n1k0** [comment] 2015-08-25 12:59
I don't have the time to properly maintain this project. I don't even have the time to triage the issues, and investigate PhantomJS 2 compatibility. 

I'd like someone to take over this very mission, possibly the whole project if it works great. If anybody's willing to do this, please say so.

**Comment by kenma9123** [comment] 2015-08-25 14:43
I think @hexid was able to make it work on PhantomJS 2.0.

**Comment by n1k0** [comment] 2015-08-25 15:13
Tests needs to be fixed, so code must be updated it seems. Also, backward compatibility should be guaranteed, which probably involves a bunch of work. That's the kind of tasks I'm talking about.

**Comment by hexid** [comment] 2015-08-27 02:26
@n1k0 I know that we need to ensure that existing scripts continue to work, but do you also want to maintain compatibility with older versions of PhantomJS?
If so, I can update my patch to maintain support for the 1.x series.

I'll keep looking into the failing tests and try to start digging through some of the open issues/PRs.

**Comment by n1k0** [comment] 2015-08-27 08:09
@hexid if it was just *me* I'd just drop support for older versions but there's a ton of scripts relying on them out there, and as we're currently on RC we can't simply declare 2.0 the only supported version for 1.0 stable.

> I'll keep looking into the failing tests and try to start digging through some of the open issues/PRs.

Thanks you **so** much!

**Comment by jcrben** [comment] 2015-10-25 17:35
if backwards compatibility is a lot of work, why not just ship a separate new version? Those who need backwards compatibility can uss the old version.

**Comment by istr** [comment] 2015-11-17 23:13
I guess that support for 2.0.0 will make sense [starting with 2.0.1](https://github.com/ariya/phantomjs/issues/12902) which is in the pipeline and worked on.

The main deal breaker seems to be [the file upload regression](https://github.com/ariya/phantomjs/issues/12506) -- it is easy to [disable the tests temporarily, which I did in my fork](https://github.com/istr/casperjs/tree/feature/phantomjs2) and you may also opt to try with [this 2.0.1 pre-release](https://github.com/skakri/phantomjs/releases/tag/2.0.1-regression-12506).

**Comment by istr** [comment] 2015-11-18 17:01
In the meantime I prepared [a version that passes self-tests on pre-built 1.9.6, 2.0.0, 2.0.1 (Ubuntu 14.04.3)](https://github.com/istr/casperjs/tree/feature/phantomjs2). Please check if this works for slimerjs and lower phantomjs versions, too.

**Comment by istr** [comment] 2015-12-01 18:49
It seems that there is [some movement](https://github.com/n1k0/casperjs/issues/1350). Lets hope that we could re-gain some traction and have 1.1 ready early Q1/2016. Any helping hands willing to join that ride are welcome.

Closing in favor of #1350.

**Closed by istr** 2015-12-01 18:49 UTC

**Comment by kenguest** [comment] 2017-03-03 10:11
there does appear to be some activity - https://github.com/casperjs/casperjs/pulse/monthly with release 1.1.14 made just a few days ago (21st February 2017).
